# Generated by Django 5.0.3 on 2024-06-23 01:05

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekendfoodfoot', '0002_alter_tabletype_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('table_type', 'date', 'time')},
        ),
    ]
