# Generated by Django 5.0.3 on 2024-06-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekendfoodfoot', '0003_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('V', 'Valide'), ('T', 'Terminé')], default='V', max_length=1),
        ),
    ]
